name: osdagbridge-env

channels:
  - osdag
  - geompy
  - conda-forge

dependencies:
  - python>=3.11,<3.13

  # main application
  - osdag::osdag

  # bridge-specific
  - matplotlib
  - fiona
  - shapely
  - scipy>=1.10.1
  - pydantic
  - xarray

  # development install
  - pip
  - pip:
    - openseespy>=3.2.2.6
    - opsvis
    - -e .